# This is a basic workflow to help you get started with Actions

name: NG-DB-API-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Node Setup
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "22"

      # Install dependencies
      - name: Install deps
        run: npm i

      # Generate environment.production.ts file dynamically
      - name: Create environment.production.ts
        run: |
          echo "Generating production environment file"
          mkdir -p src/environments
          echo "export const environment = { production: true };" > src/environments/environment.production.ts

      # Build app for production
      - name: Build for production
        run: npm run build --configuration production

      # Deploy to GitHub pages
      - name: Deploy to Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/ng-dragon-ball-api/browser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
